{% set name = "msbuild" %}
{% set version = "17.12.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dotnet/msbuild/archive/v{{ version }}.tar.gz
  sha256: 1aa44f0aca88e45f6a77d90f0c4c1edc1def1236f434fd8c35d8bfc28200800f

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - jq
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - MSBuild --help

about:
  home: https://github.com/dotnet/msbuild
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The Microsoft Build Engine (MSBuild) is the build platform for .NET and Visual Studio.
  dev_url: https://github.com/dotnet/msbuild

extra:
  recipe-maintainers:
    - danielnachun
