context:
  version: "17.13.8"

package:
  name: msbuild
  version: ${{ version }}

source:
  url: https://github.com/dotnet/msbuild/archive/v${{ version }}.tar.gz
  sha256: ff0473bf7db8fbddd565cc6e7f49228e29ae45aa474427fa3cc3fcd1c32678d0

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - jq
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - MSBuild --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The Microsoft Build Engine (MSBuild) is the build platform for .NET and Visual Studio.
  homepage: https://github.com/dotnet/msbuild
  repository: https://github.com/dotnet/msbuild

extra:
  recipe-maintainers:
    - danielnachun
