context:
  version: "18.10.1"

package:
  name: msbuild
  version: ${{ version }}

source:
  url: https://github.com/dotnet/msbuild/archive/v${{ version }}.tar.gz
  sha256: 35d86f77bcc104207bf11551e75c823e1484ac038eaace7e1f9376dc7c0e4488

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - jq
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - MSBuild --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The Microsoft Build Engine (MSBuild) is the build platform for .NET and Visual Studio.
  homepage: https://github.com/dotnet/msbuild
  repository: https://github.com/dotnet/msbuild

extra:
  recipe-maintainers:
    - danielnachun
