context:
  version: "18.9.6"

package:
  name: msbuild
  version: ${{ version }}

source:
  url: https://github.com/dotnet/msbuild/archive/v${{ version }}.tar.gz
  sha256: f1b0874df9a42e8d2e47f83f5a31f878b19942767eed8c58e3fe34705e6af74f

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - jq
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - MSBuild --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The Microsoft Build Engine (MSBuild) is the build platform for .NET and Visual Studio.
  homepage: https://github.com/dotnet/msbuild
  repository: https://github.com/dotnet/msbuild

extra:
  recipe-maintainers:
    - danielnachun
