context:
  version: "18.3.3"

package:
  name: msbuild
  version: ${{ version }}

source:
  url: https://github.com/dotnet/msbuild/archive/v${{ version }}.tar.gz
  sha256: fafd01925e45ed2e43f8754513d0794b96acebe65ded6c3bb1a43327e7951194

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - jq
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - MSBuild --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The Microsoft Build Engine (MSBuild) is the build platform for .NET and Visual Studio.
  homepage: https://github.com/dotnet/msbuild
  repository: https://github.com/dotnet/msbuild

extra:
  recipe-maintainers:
    - danielnachun
