context:
  version: "18.6.3"

package:
  name: msbuild
  version: ${{ version }}

source:
  url: https://github.com/dotnet/msbuild/archive/v${{ version }}.tar.gz
  sha256: d0530d13ece7959381b027b1fa56ec926aa9f2ce3e0465ca0fb242ed6bd05826

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - jq
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - MSBuild --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The Microsoft Build Engine (MSBuild) is the build platform for .NET and Visual Studio.
  homepage: https://github.com/dotnet/msbuild
  repository: https://github.com/dotnet/msbuild

extra:
  recipe-maintainers:
    - danielnachun
